# Generated by Django 6.1.1 on 2026-09-25 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=150)),
                ('short_description', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('technologies', models.JSONField(default=list)),
                ('image', models.ImageField(upload_to='projects/')),
                ('featured', models.BooleanField(default=False)),
                ('github', models.URLField(blank=True, null=True)),
                ('demo', models.URLField(blank=True, null=True)),
                ('overview', models.TextField(blank=True)),
                ('challenge', models.TextField(blank=True)),
                ('solution', models.TextField(blank=True)),
                ('features', models.JSONField(default=list)),
                ('architecture', models.JSONField(default=list)),
                ('learnings', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-featured', '-created_at'],
            },
        ),
    ]
