# Generated by Django 6.1.1 on 2026-09-26 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_migrate_project_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
    ]
